/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.bd.telas;
import java.sql.*;
import br.com.bd.dao.ModuloConexao;
import javax.swing.JOptionPane;
/**
 *
 * @author Dayana
 */
public class TelaUpLogin extends javax.swing.JInternalFrame {
    Connection conexao_Postgres = null;
    PreparedStatement pst = null;
    PreparedStatement pst1 = null;
    ResultSet rs = null;
    /**
     * Creates new form TelaUpLogin
     */
    public TelaUpLogin() {
        initComponents();
        conexao_Postgres = ModuloConexao.conector();
    }
    
    //alterar login do usuario
    private  void alterar(){
        String sql = "SELECT * FROM USUARIOS WHERE cpf_user=?";
        String sql2 = "UPDATE USUARIOS SET  login=?, senha=? WHERE cpf_user=?"; 
        
        try {
            pst1 = conexao_Postgres.prepareStatement(sql);
            pst = conexao_Postgres.prepareStatement(sql2);
            pst.setString(1, txt_up_log_login.getText());
            pst.setString(2, txt_up_log_senha.getText());
            pst.setString(3, txt_up_log_cpf.getText());
            
            pst1.setString(1, txt_up_log_cpf.getText());
            rs = pst1.executeQuery();
            
            if(rs.next()){
                if(txt_up_log_cpf.getText().isEmpty() || txt_up_log_senha.getText().isEmpty() || txt_up_log_login.getText().isEmpty()){
                    JOptionPane.showMessageDialog(null, "Preencha todos os campos!");
                }
                else{
                    //atualizando a tabela usuario com os dados do formulario
                    int alt = pst.executeUpdate();
                    if(alt > 0){
                        JOptionPane.showMessageDialog(null, "Login alterado com sucesso!");
                        //as linhas abaixo "limpam" os campos
                        txt_up_log_login.setText(null);
                        txt_up_log_senha.setText(null);
                        txt_up_log_cpf.setText(null);
                    }else{
                        JOptionPane.showMessageDialog(null, "Usuário não encontrado!");
                    } 
                }
        
            }else{
                JOptionPane.showMessageDialog(null, "Usuário não encontrado!");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btn_up_log = new javax.swing.JButton();
        txt_up_log_cpf = new javax.swing.JTextField();
        txt_up_log_login = new javax.swing.JTextField();
        txt_up_log_senha = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setPreferredSize(new java.awt.Dimension(677, 491));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("* CPF:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("* Login:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("* Senha:");

        btn_up_log.setBackground(new java.awt.Color(153, 153, 153));
        btn_up_log.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bd/icones/update.png"))); // NOI18N
        btn_up_log.setToolTipText("Atualizar");
        btn_up_log.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_up_log.setPreferredSize(new java.awt.Dimension(70, 70));
        btn_up_log.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_up_logActionPerformed(evt);
            }
        });

        txt_up_log_cpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_up_log_cpfActionPerformed(evt);
            }
        });

        jLabel4.setText("* Campos Obrigatórios");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_up_log, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_up_log_cpf)
                            .addComponent(txt_up_log_login)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txt_up_log_senha, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 196, Short.MAX_VALUE)))))
                .addGap(74, 74, 74))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_up_log_cpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_up_log_login, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_up_log_senha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addComponent(btn_up_log, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(84, 84, 84)
                .addComponent(jLabel4)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_up_log_cpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_up_log_cpfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_up_log_cpfActionPerformed

    private void btn_up_logActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_up_logActionPerformed
        // chamando metodo alterar login
        alterar();
    }//GEN-LAST:event_btn_up_logActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_up_log;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txt_up_log_cpf;
    private javax.swing.JTextField txt_up_log_login;
    private javax.swing.JTextField txt_up_log_senha;
    // End of variables declaration//GEN-END:variables
}
